export const REGISTER_NAME_CHANGE = "REGISTER_NAME_CHANGE";
export const REGISTER_EMAIL_CHANGE = "REGISTER_EMAIL_CHANGE";
export const REGISTER_PASSWORD_CHANGE = "REGISTER_PASSWORD_CHANGE";
export const LOGIN_USERNAME_CHANGE = "LOGIN_USERNAME_CHANGE";
export const LOGIN_PASSWORD_CHANGE = "LOGIN_PASSWORD_CHANGE";
